import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart'; // Import google_fonts
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart'; // Import FirebaseAuth
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:quiz_master/screens/login_screen.dart';
import 'package:quiz_master/screens/home_screen.dart'; // Import HomeScreen

// Import the generated localization delegate
import 'package:flutter_gen/gen_l10n/app_localizations.dart';

void main() async {
  // Ensure Flutter bindings are initialized before Firebase
  WidgetsFlutterBinding.ensureInitialized();
  // Initialize Firebase
  await Firebase.initializeApp(
      // options: DefaultFirebaseOptions.currentPlatform, // Use this if generated by FlutterFire CLI
      );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      // Use AppLocalizations for the title once context is available,
      // or keep it hardcoded if needed before localization is ready.
      // onGenerateTitle: (context) => AppLocalizations.of(context)!.appTitle,
      title: 'Quiz Master', // Hardcoded title for initial load
      theme: ThemeData(
        // Generate ColorScheme from a seed color for Material 3
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.blueAccent, // Changed seed color
          brightness: Brightness.light, // Explicitly set brightness
        ),
        // Apply the Cairo font theme using google_fonts
        textTheme: GoogleFonts.cairoTextTheme(
          Theme.of(context).textTheme, // Apply Cairo to default text theme
        ),
        // Ensure Material 3 features are used
        useMaterial3: true,
        // Optional: Customize specific components
        appBarTheme: AppBarTheme(
          backgroundColor: Colors.blueAccent.shade700, // Darker AppBar
          foregroundColor: Colors.white, // White title/icons
          elevation: 4,
        ),
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
             // backgroundColor: Colors.blueAccent.shade700, // Button color from scheme
             // foregroundColor: Colors.white, // Button text color from scheme
             padding: const EdgeInsets.symmetric(vertical: 12, horizontal: 20),
             shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
          ),
        ),
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      // --- Localization Setup ---
      localizationsDelegates: const [
        AppLocalizations.delegate, // Add the generated delegate
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: const [
        Locale('en', ''), // English, no country code
        Locale('ar', ''), // Arabic, no country code
      ],
      // Set the initial locale based on device settings or user preference
      // locale: ...,
      // --------------------------
      debugShowCheckedModeBanner: false, // Hide debug banner
      // Use StreamBuilder to listen to auth state changes
      home: StreamBuilder<User?>(
        stream: FirebaseAuth.instance.authStateChanges(),
        builder: (context, snapshot) {
          // Show loading indicator while checking auth state
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Scaffold(
              body: Center(child: CircularProgressIndicator()),
            );
          }
          // If user is logged in, show HomeScreen
          if (snapshot.hasData) {
            return const HomeScreen();
          }
          // If user is not logged in, show LoginScreen
          return const LoginScreen();
        },
      ),
    );
  }
}
